SELECT *
FROM BOARDS;

-- 계층 페이징
SELECT
 POST_ID
--    ,USER_NAME
--    ,PW
--    ,TITLE
,REPLY_IDX
--    ,REPLY_GROUP_SEQ
--    ,REPLY_DEPTH
--    ,BOARD_NAME
,UPDATE_DATE
,
CASE WHEN REPLY_GROUP_SEQ = 0 THEN POST_ID ELSE REPLY_GROUP_SEQ END AS REPLY_GROUP_SEQ
, CASE WHEN REPLY_GROUP_SEQ = 0 THEN UPDATE_DATE PRIOR UPDATE_DATE END -- AS PATENTSORT
,
CASE WHEN REPLY_GROUP_SEQ = 0 THEN STR_TO_DATE('2000101','YYYYMMDD') ELSE UPDATE_DATE END AS SORT
--   ,LEVEL AS REPLY_DEPTH
FROM BOARDS
WHERE 1=1 START WITH REPLY_GROUP_SEQ = 0
CONNECT BY PRIOR POST_ID = REPLY_GROUP_SEQ;
--
WITH RECURSIVE p AS (
SELECT *
FROM BOARDS
WHERE POST_ID = 26 UNION
SELECT c.*
FROM BOARDS AS c, p
WHERE p.REPLY_GROUP_ID = c.POST_ID
)
SELECT *
FROM p
ORDER BY POST_ID ASC
LIMIT 15;

--
SELECT *
FROM BOARDS
ORDER BY UPDATE_DATE DESC; ALTER TABLE IMDB.REPLY MODIFY USER_NAME NVARCHAR(20); DESC REPLY; DESC BOARDS; COMMIT;
INSERT INTO BOARDS (POST_ID,TITLE,USER_NAME,PW, CONTENTS,BOARD_NAME)
VALUE(NEXTVAL(BOARDS_SEQ),'TITLE1','USER1','1','TESTCONTENTS','freeBoard');
SELECT DATE_FORMAT(UPDATE_DATE,'%Y-%m-%d %H:%i:%S')
FROM BOARDS;

/* reply */
SELECT *
FROM REPLY; ALTER TABLE BOARDS
DROP COLUMN REPLY_GROUP_ID; COMMIT; ALTER TABLE BOARDS MODIFY UPDATE_DATE TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP;
INSERT INTO REPLY (TITLE,PW, POST_GROUP_ID,CREATE_DATE,UPDATE_DATE) VALUES('TITLE1','1',1001, DEFAULT, DEFAULT); ALTER TABLE REPLY MODIFY UPDATE_DATE TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP;
SELECT DATE_FORMAT(CREATE_DATE,'%Y-%m-%d %H:%i:%S')
FROM	REPLY
ORDER BY CREATE_DATE DESC; ALTER TABLE REPLY ADD COLUMN VOTE_DOWN INT UNSIGNED NOT NULL DEFAULT 0;

SELECT 
	A.*
	,( VOTE_UP + VOTE_DOWN ) AS VOTECNT
FROM 
(
	SELECT TITLE
	, POST_ID
	, VOTE_UP
	, VOTE_DOWN
	, DATE_FORMAT(CREATE_DATE, '%Y-%m-%d %H:%i:%S') AS CREATE_DATE
	FROM REPLY
	WHERE POST_GROUP_ID = '5013'
) A
ORDER BY VOTECNT DESC;